# Generated by Django 5.0.3 on 2024-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nususario', models.CharField(max_length=50)),
                ('correou', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id_comunidad', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrolladores',
            fields=[
                ('iddev', models.AutoField(primary_key=True, serialize=False)),
                ('correodev_1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('idfinanzas', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Perfildev',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(max_length=50)),
                ('correo_perfil', models.CharField(max_length=100)),
                ('github_perfil', models.CharField(max_length=100)),
                ('youtube_perfil', models.CharField(max_length=100)),
                ('twitch_perfil', models.CharField(max_length=100)),
                ('facebook_perfil', models.CharField(max_length=100)),
                ('instagram_perfil', models.CharField(max_length=100)),
                ('titulo_proyecto', models.CharField(max_length=50)),
                ('categoria_proyecto', models.CharField(max_length=100)),
            ],
        ),
    ]
